### ISSUE TITLE
Fails to build on lineage-16.0-enforcing

### ISSUE THREAD

**Issue by JarlPenguin** [montanadevelopment/device_motorola_montana#2]
Works on old repo. Something related to NFC. I'm resyncing right now, don't know if it'll help.

https://hasteb.in/akorirej.makefile

**Comment by JarlPenguin** [comment]
Builds fine with old device tree + new vendor after capitalizing M in Montana-vendor.mk

**Comment by JarlPenguin** [comment]
@AsdMonio bump

**Comment by AsdMonio** [comment]
This seems to be a LineageOS issue, since the error is from the NFC app package. IIRC it also happened to me using the old trees. A fix for now is to just comment out the line, since it's just a log call, that's what I did originally. Another option which seems to work is to add a variable conversion before the "handle" parameter (packages/apps/Nfc/nxp/jni/com_android_nfc_NativeNfcTag.cpp, line 601):
`ALOGE("phLibNfc_RemoteDev_Disconnect(%x) returned 0x%04x[%s]", (int) handle, status, nfc_jni_get_status_name(status));`

**Comment by JarlPenguin** [comment]
Hmm, alright. I'll try building with the new tree ASAP, then I'll close this issue if there are no errors.

**Comment by JarlPenguin** [comment]
Issue solved with NFC fixes https://github.com/montanadevelopment/device_motorola_montana/commit/278d73f5e610947bed274a89e4270e7c0616a973 and https://github.com/montanadevelopment/device_motorola_montana/commit/c993f326f30536af1412b3cf106f2bba49e046f6
